import 'package:flutter/material.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';

final List<IconData> interfaceEssentials = [
  FontAwesomeIcons.compass,
  FontAwesomeIcons.fire,
  FontAwesomeIcons.fireAlt,
  FontAwesomeIcons.lightbulb,
  FontAwesomeIcons.mars,
  FontAwesomeIcons.venus,
  FontAwesomeIcons.thumbsUp,
  FontAwesomeIcons.solidThumbsUp,
  FontAwesomeIcons.thumbsDown,
  FontAwesomeIcons.solidThumbsDown,
  FontAwesomeIcons.camera,
  FontAwesomeIcons.cameraRetro,
//  FontAwesomeIcons.camera - alt,
  FontAwesomeIcons.image,
  FontAwesomeIcons.bars,
  FontAwesomeIcons.certificate,
  FontAwesomeIcons.check,
  FontAwesomeIcons.checkCircle,
  FontAwesomeIcons.checkSquare,
  FontAwesomeIcons.cog,
  FontAwesomeIcons.ellipsisH,
  FontAwesomeIcons.ellipsisV,
//  FontAwesomeIcons.elipsis - v - alt,
//  FontAwesomeIcons.elipsis - h - alt,
  FontAwesomeIcons.hashtag,
  FontAwesomeIcons.home,
  FontAwesomeIcons.info,
  FontAwesomeIcons.infoCircle,
//  FontAwesomeIcons.infoSquare,
  FontAwesomeIcons.medal,
  FontAwesomeIcons.question,
  FontAwesomeIcons.questionCircle,
  FontAwesomeIcons.solidQuestionCircle,
  FontAwesomeIcons.search,
  FontAwesomeIcons.star,
  FontAwesomeIcons.times,
  FontAwesomeIcons.timesCircle,
//  FontAwesomeIcons.timesHexagom,
//  FontAwesomeIcons.timesoctagon,
//  FontAwesomeIcons.timessquare,
  FontAwesomeIcons.trash,
  FontAwesomeIcons.trashAlt,
  FontAwesomeIcons.trophy,
//  FontAwesomeIcons.trophyAlt,
  FontAwesomeIcons.user,
  FontAwesomeIcons.userAlt,
  FontAwesomeIcons.userCircle,
  FontAwesomeIcons.bookmark,
  FontAwesomeIcons.images,
  FontAwesomeIcons.male,
  FontAwesomeIcons.map,
  FontAwesomeIcons.shoppingBag,
  FontAwesomeIcons.shoppingBasket,
  FontAwesomeIcons.shoppingCart,
  FontAwesomeIcons.bullhorn,
  FontAwesomeIcons.megaport,
  FontAwesomeIcons.newspaper,
  FontAwesomeIcons.ban,
  FontAwesomeIcons.lock,
  FontAwesomeIcons.receipt,
  FontAwesomeIcons.store,
  FontAwesomeIcons.storeAlt,
  FontAwesomeIcons.userFriends,
  FontAwesomeIcons.users,
  FontAwesomeIcons.female,
//  FontAwesomeIcons.alarm,
//  FontAwesomeIcons.alarmExclamation,
  FontAwesomeIcons.bell,
//  FontAwesomeIcons.bellOn,
  FontAwesomeIcons.bellSlash,
  FontAwesomeIcons.solidBellSlash,
  FontAwesomeIcons.exclamation,
  FontAwesomeIcons.exclamationCircle,
  FontAwesomeIcons.exclamationTriangle,
  FontAwesomeIcons.skullCrossbones,
  FontAwesomeIcons.angleLeft,
  FontAwesomeIcons.angleRight,
  FontAwesomeIcons.arrowLeft,
  FontAwesomeIcons.arrowRight,
  FontAwesomeIcons.externalLinkAlt,
  FontAwesomeIcons.externalLinkSquareAlt,
  FontAwesomeIcons.locationArrow,
//  FontAwesomeIcons.album,
//  FontAwesomeIcons.album - collection,
];

List<List<dynamic>> convertCategoryToItems(
    List<IconData> category, String title) {
  List<List<dynamic>> sumList = [
    [title]
  ];

  for (var i = 0; i <= category.length - 1; i = i + 5) {
    sumList.add([
      category[i],
      i + 1 > category.length - 1 ? null : category[i + 1],
      i + 2 > category.length - 1 ? null : category[i + 2],
      i + 3 > category.length - 1 ? null : category[i + 3],
      i + 4 > category.length - 1 ? null : category[i + 4],
    ]);
  }

  return sumList;
}

final List<List<dynamic>> allIconsList = [
  ...convertCategoryToItems(interfaceEssentials, 'Interface Essentials'),
//  ...convertCategoryToItems(animals, 'Animals & Nature'),
//  ...convertCategoryToItems(foods, 'Food & Drink'),
//  ...convertCategoryToItems(travel, 'Travel & Places'),
//  ...convertCategoryToItems(smileys, 'Smileys & People'),
//  ...convertCategoryToItems(objects, 'Objects'),
//  ...convertCategoryToItems(symbols, 'Symbols'),
//  ...convertCategoryToItems(flags, 'Flags'),
];
