import 'package:flutter/material.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';

final List<IconData> interfaceEssentials = [
  FontAwesomeIcons.addressBook,
  FontAwesomeIcons.addressCard,
//  FontAwesomeIcons.alarmClock,
//  FontAwesomeIcons.alarmExclamation,
//  FontAwesomeIcons.album,
//  FontAwesomeIcons.albumCollection,
//  FontAwesomeIcons.analytics,
  FontAwesomeIcons.angleLeft,
  FontAwesomeIcons.angleRight,
  FontAwesomeIcons.archive,
  FontAwesomeIcons.arrowLeft,
  FontAwesomeIcons.arrowRight,
  FontAwesomeIcons.asterisk,
  FontAwesomeIcons.at,
  FontAwesomeIcons.atom,
//  FontAwesomeIcons.atomAlt,
  FontAwesomeIcons.award,
//  FontAwesomeIcons.badge,
//  FontAwesomeIcons.badgeCheck,
//  FontAwesomeIcons.bagsShopping,
  FontAwesomeIcons.ban,
  FontAwesomeIcons.bars,
  FontAwesomeIcons.bell,
//  FontAwesomeIcons.bellOn,
  FontAwesomeIcons.bellSlash,
//  FontAwesomeIcons.bells,
  FontAwesomeIcons.binoculars,
  FontAwesomeIcons.birthdayCake,
  FontAwesomeIcons.bolt,
  FontAwesomeIcons.book,
//  FontAwesomeIcons.bookAlt,
  FontAwesomeIcons.bookOpen,
  FontAwesomeIcons.bookmark,
//  FontAwesomeIcons.books,
  FontAwesomeIcons.briefcase,
  FontAwesomeIcons.bug,
  FontAwesomeIcons.bullhorn,
  FontAwesomeIcons.calendar,
  FontAwesomeIcons.calendarAlt,
  FontAwesomeIcons.camera,
//  FontAwesomeIcons.cameraAlt,
//  FontAwesomeIcons.cameraMovie,
  FontAwesomeIcons.cameraRetro,
  FontAwesomeIcons.car,
  FontAwesomeIcons.carAlt,
  FontAwesomeIcons.certificate,
  FontAwesomeIcons.chartArea,
  FontAwesomeIcons.chartBar,
  FontAwesomeIcons.chartLine,
//  FontAwesomeIcons.chartLineDown,
  FontAwesomeIcons.chartPie,
//  FontAwesomeIcons.chartPieAlt,
  FontAwesomeIcons.check,
  FontAwesomeIcons.checkCircle,
  FontAwesomeIcons.checkSquare,
  FontAwesomeIcons.clock,
  FontAwesomeIcons.cloud,
  FontAwesomeIcons.coffee,
  FontAwesomeIcons.cog,
  FontAwesomeIcons.coins,
  FontAwesomeIcons.columns,
  FontAwesomeIcons.comment,
  FontAwesomeIcons.commentAlt,
//  FontAwesomeIcons.commentAltDots,
  FontAwesomeIcons.commentDots,
//  FontAwesomeIcons.commentLines,
  FontAwesomeIcons.comments,
//  FontAwesomeIcons.commentsAlt,
  FontAwesomeIcons.compass,
  FontAwesomeIcons.copy,
  FontAwesomeIcons.database,
//  FontAwesomeIcons.desktopAlt,
  FontAwesomeIcons.desktop,
  FontAwesomeIcons.dollarSign,
  FontAwesomeIcons.edit,
//  FontAwesomeIcons.elipsisH,
//  FontAwesomeIcons.elipsisHAlt,
//  FontAwesomeIcons.elipsisV,
//  FontAwesomeIcons.elipsisVAlt,
  FontAwesomeIcons.ellipsisH,
//  FontAwesomeIcons.ellipsisHAlt,
  FontAwesomeIcons.ellipsisV,
//  FontAwesomeIcons.ellipsisVAlt,
  FontAwesomeIcons.envelope,
  FontAwesomeIcons.envelopeOpen,
  FontAwesomeIcons.euroSign,
  FontAwesomeIcons.exclamation,
  FontAwesomeIcons.exclamationCircle,
//  FontAwesomeIcons.exclamationSquare,
  FontAwesomeIcons.exclamationTriangle,
//  FontAwesomeIcons.externalLink,
  FontAwesomeIcons.externalLinkAlt,
//  FontAwesomeIcons.externalLinkSquare,
  FontAwesomeIcons.externalLinkSquareAlt,
  FontAwesomeIcons.eye,
  FontAwesomeIcons.female,
  FontAwesomeIcons.file,
  FontAwesomeIcons.fileAlt,
  FontAwesomeIcons.film,
//  FontAwesomeIcons.filmAlt,
  FontAwesomeIcons.fire,
  FontAwesomeIcons.fireAlt,
//  FontAwesomeIcons.flagAlt,
  FontAwesomeIcons.folder,
  FontAwesomeIcons.folderOpen,
//  FontAwesomeIcons.folders,
  FontAwesomeIcons.gem,
  FontAwesomeIcons.gift,
//  FontAwesomeIcons.giftCard,
  FontAwesomeIcons.gifts,
  FontAwesomeIcons.glasses,
  FontAwesomeIcons.globe,
//  FontAwesomeIcons.globeStand,
  FontAwesomeIcons.graduationCap,
  FontAwesomeIcons.hashtag,
  FontAwesomeIcons.heart,
//  FontAwesomeIcons.heartCircle,
//  FontAwesomeIcons.heartSquare,
  FontAwesomeIcons.home,
//  FontAwesomeIcons.homeAlt,
//  FontAwesomeIcons.homeLg,
//  FontAwesomeIcons.homeLgAlt,
  FontAwesomeIcons.hourglass,
  FontAwesomeIcons.hourglassEnd,
  FontAwesomeIcons.hourglassHalf,
  FontAwesomeIcons.hourglassStart,
  FontAwesomeIcons.idCard,
  FontAwesomeIcons.image,
  FontAwesomeIcons.images,
  FontAwesomeIcons.info,
  FontAwesomeIcons.infoCircle,
//  FontAwesomeIcons.infoSquare,
  FontAwesomeIcons.key,
  FontAwesomeIcons.landmark,
//  FontAwesomeIcons.landmarkAlt,
  FontAwesomeIcons.layerGroup,
  FontAwesomeIcons.lightbulb,
  FontAwesomeIcons.link,
  FontAwesomeIcons.list,
  FontAwesomeIcons.listAlt,
//  FontAwesomeIcons.listMusic,
  FontAwesomeIcons.listOl,
  FontAwesomeIcons.listUl,
  FontAwesomeIcons.locationArrow,
  FontAwesomeIcons.lock,
//  FontAwesomeIcons.lockAlt,
  FontAwesomeIcons.male,
  FontAwesomeIcons.map,
  FontAwesomeIcons.mapMarked,
  FontAwesomeIcons.mapMarkedAlt,
  FontAwesomeIcons.mapMarker,
  FontAwesomeIcons.mapMarkerAlt,
  FontAwesomeIcons.mapSigns,
  FontAwesomeIcons.mars,
  FontAwesomeIcons.medal,
//  FontAwesomeIcons.megaphone,
  FontAwesomeIcons.microphone,
  FontAwesomeIcons.microphoneAlt,
  FontAwesomeIcons.mobile,
  FontAwesomeIcons.mobileAlt,
//  FontAwesomeIcons.mobileAndroid,
//  FontAwesomeIcons.mobileAndroidAlt,
  FontAwesomeIcons.moneyBill,
  FontAwesomeIcons.moneyBillAlt,
  FontAwesomeIcons.moneyBillWave,
  FontAwesomeIcons.moneyBillWaveAlt,
  FontAwesomeIcons.music,
//  FontAwesomeIcons.musicAlt,
  FontAwesomeIcons.newspaper,
  FontAwesomeIcons.palette,
  FontAwesomeIcons.paperPlane,
  FontAwesomeIcons.paperclip,
  FontAwesomeIcons.pen,
  FontAwesomeIcons.penAlt,
//  FontAwesomeIcons.pencil,
  FontAwesomeIcons.pencilAlt,
  FontAwesomeIcons.phone,
  FontAwesomeIcons.phoneAlt,
  FontAwesomeIcons.phoneSquare,
  FontAwesomeIcons.phoneSquareAlt,
  FontAwesomeIcons.piggyBank,
  FontAwesomeIcons.plane,
//  FontAwesomeIcons.planeAlt,
  FontAwesomeIcons.poll,
  FontAwesomeIcons.pollH,
  FontAwesomeIcons.question,
  FontAwesomeIcons.questionCircle,
//  FontAwesomeIcons.questionSquare,
  FontAwesomeIcons.quoteLeft,
  FontAwesomeIcons.quoteRight,
  FontAwesomeIcons.receipt,
  FontAwesomeIcons.rocket,
  FontAwesomeIcons.rss,
  FontAwesomeIcons.rssSquare,
//  FontAwesomeIcons.sack,
//  FontAwesomeIcons.sackDollar,
  FontAwesomeIcons.scroll,
  FontAwesomeIcons.search,
  FontAwesomeIcons.server,
  FontAwesomeIcons.shoppingBag,
  FontAwesomeIcons.shoppingBasket,
  FontAwesomeIcons.shoppingCart,
  FontAwesomeIcons.skullCrossbones,
  FontAwesomeIcons.slidersH,
//  FontAwesomeIcons.slidersHSquare,
  FontAwesomeIcons.smile,
//  FontAwesomeIcons.sparkles,
  FontAwesomeIcons.star,
//  FontAwesomeIcons.stars,
  FontAwesomeIcons.stickyNote,
  FontAwesomeIcons.stopwatch,
  FontAwesomeIcons.store,
  FontAwesomeIcons.storeAlt,
  FontAwesomeIcons.stream,
  FontAwesomeIcons.swatchbook,
  FontAwesomeIcons.table,
  FontAwesomeIcons.tablet,
  FontAwesomeIcons.tabletAlt,
//  FontAwesomeIcons.tabletAndroid,
//  FontAwesomeIcons.tabletAndroidAlt,
//  FontAwesomeIcons.tachometer,
  FontAwesomeIcons.tachometerAlt,
  FontAwesomeIcons.tag,
  FontAwesomeIcons.tags,
  FontAwesomeIcons.tasks,
  FontAwesomeIcons.th,
  FontAwesomeIcons.thLarge,
  FontAwesomeIcons.thList,
  FontAwesomeIcons.theaterMasks,
  FontAwesomeIcons.thumbsDown,
  FontAwesomeIcons.thumbsUp,
//  FontAwesomeIcons.ticket,
  FontAwesomeIcons.ticketAlt,
  FontAwesomeIcons.times,
  FontAwesomeIcons.timesCircle,
//  FontAwesomeIcons.timesHexagom,
//  FontAwesomeIcons.timesHexagon,
//  FontAwesomeIcons.timesOctagon,
//  FontAwesomeIcons.timesSquare,
  FontAwesomeIcons.toolbox,
  FontAwesomeIcons.tools,
  FontAwesomeIcons.trash,
  FontAwesomeIcons.trashAlt,
  FontAwesomeIcons.trophy,
//  FontAwesomeIcons.trophyAlt,
  FontAwesomeIcons.university,
//  FontAwesomeIcons.usdCircle,
//  FontAwesomeIcons.usdSquare,
  FontAwesomeIcons.user,
  FontAwesomeIcons.userAlt,
  FontAwesomeIcons.userCircle,
  FontAwesomeIcons.userFriends,
  FontAwesomeIcons.userGraduate,
  FontAwesomeIcons.users,
//  FontAwesomeIcons.usersClass,
  FontAwesomeIcons.utensils,
//  FontAwesomeIcons.utensilsAlt,
  FontAwesomeIcons.venus,
  FontAwesomeIcons.video,
  FontAwesomeIcons.wallet,
  FontAwesomeIcons.wifi,
//  FontAwesomeIcons.window,
//  FontAwesomeIcons.windowAlt,
  FontAwesomeIcons.wrench,
];

final List<IconData> activity = [
  FontAwesomeIcons.guitar,
  FontAwesomeIcons.basketballBall,
  FontAwesomeIcons.bicycle,
  FontAwesomeIcons.biking,
  FontAwesomeIcons.burn,
  FontAwesomeIcons.drum,
  FontAwesomeIcons.footballBall,
  FontAwesomeIcons.gamepad,
  FontAwesomeIcons.guitar,
  FontAwesomeIcons.heartbeat,
  FontAwesomeIcons.hiking,
  FontAwesomeIcons.hockeyPuck,
  FontAwesomeIcons.paintRoller,
  FontAwesomeIcons.running,
  FontAwesomeIcons.shoePrints,
  FontAwesomeIcons.skiing,
  FontAwesomeIcons.skiingNordic,
  FontAwesomeIcons.snowboarding,
  FontAwesomeIcons.spa,
  FontAwesomeIcons.swimmer,
  FontAwesomeIcons.tableTennis,
  FontAwesomeIcons.volleyballBall,
  FontAwesomeIcons.walking,
];

final List<IconData> animalsAndNature = [
  FontAwesomeIcons.cat,
  FontAwesomeIcons.cloudSun,
  FontAwesomeIcons.crow,
  FontAwesomeIcons.dog,
  FontAwesomeIcons.dove,
  FontAwesomeIcons.dragon,
  FontAwesomeIcons.feather,
  FontAwesomeIcons.featherAlt,
  FontAwesomeIcons.horse,
  FontAwesomeIcons.horseHead,
  FontAwesomeIcons.leaf,
  FontAwesomeIcons.moon,
  FontAwesomeIcons.mountain,
  FontAwesomeIcons.paw,
  FontAwesomeIcons.seedling,
  FontAwesomeIcons.snowflake,
  FontAwesomeIcons.spider,
  FontAwesomeIcons.sun,
  FontAwesomeIcons.tree,
  FontAwesomeIcons.water,
  FontAwesomeIcons.wind,
];

final List<IconData> facesAndClothing = [
  FontAwesomeIcons.angry,
  FontAwesomeIcons.baby,
  FontAwesomeIcons.babyCarriage,
  FontAwesomeIcons.brain,
  FontAwesomeIcons.businessTime,
  FontAwesomeIcons.chessKing,
  FontAwesomeIcons.chessQueen,
  FontAwesomeIcons.dizzy,
  FontAwesomeIcons.fistRaised,
  FontAwesomeIcons.flushed,
  FontAwesomeIcons.frown,
  FontAwesomeIcons.frownOpen,
  FontAwesomeIcons.ghost,
  FontAwesomeIcons.grimace,
  FontAwesomeIcons.grin,
  FontAwesomeIcons.grinAlt,
  FontAwesomeIcons.grinBeam,
  FontAwesomeIcons.grinBeamSweat,
  FontAwesomeIcons.grinHearts,
  FontAwesomeIcons.grinSquint,
  FontAwesomeIcons.grinSquintTears,
  FontAwesomeIcons.grinStars,
  FontAwesomeIcons.grinTears,
  FontAwesomeIcons.grinTongue,
  FontAwesomeIcons.grinTongueSquint,
  FontAwesomeIcons.grinTongueWink,
  FontAwesomeIcons.grinWink,
  FontAwesomeIcons.handHolding,
  FontAwesomeIcons.handHoldingHeart,
  FontAwesomeIcons.handHoldingUsd,
  FontAwesomeIcons.handMiddleFinger,
  FontAwesomeIcons.handPaper,
  FontAwesomeIcons.handPeace,
  FontAwesomeIcons.handPointDown,
  FontAwesomeIcons.handPointLeft,
  FontAwesomeIcons.handPointRight,
  FontAwesomeIcons.handPointUp,
  FontAwesomeIcons.handPointer,
  FontAwesomeIcons.handRock,
  FontAwesomeIcons.handScissors,
  FontAwesomeIcons.handSparkles,
  FontAwesomeIcons.handSpock,
  FontAwesomeIcons.hands,
  FontAwesomeIcons.handsHelping,
  FontAwesomeIcons.handsWash,
  FontAwesomeIcons.handshake,
  FontAwesomeIcons.hatCowboy,
  FontAwesomeIcons.hatCowboySide,
  FontAwesomeIcons.hospitalUser,
  FontAwesomeIcons.kiss,
  FontAwesomeIcons.kissBeam,
  FontAwesomeIcons.kissWinkHeart,
  FontAwesomeIcons.laugh,
  FontAwesomeIcons.laughBeam,
  FontAwesomeIcons.laughSquint,
  FontAwesomeIcons.laughWink,
  FontAwesomeIcons.mask,
  FontAwesomeIcons.meh,
  FontAwesomeIcons.mehBlank,
  FontAwesomeIcons.mehRollingEyes,
  FontAwesomeIcons.poo,
  FontAwesomeIcons.prayingHands,
  FontAwesomeIcons.robot,
  FontAwesomeIcons.sadCry,
  FontAwesomeIcons.sadTear,
  FontAwesomeIcons.shoePrints,
  FontAwesomeIcons.smileBeam,
  FontAwesomeIcons.smileWink,
  FontAwesomeIcons.smoking,
  FontAwesomeIcons.socks,
  FontAwesomeIcons.surprise,
  FontAwesomeIcons.tired,
  FontAwesomeIcons.tshirt,
  FontAwesomeIcons.userAstronaut,
  FontAwesomeIcons.userLock,
  FontAwesomeIcons.userSecret,
  FontAwesomeIcons.userShield,
  FontAwesomeIcons.userTie,
];

const List<IconData> foodAndDrinks = [
  FontAwesomeIcons.cannabis,
  FontAwesomeIcons.appleAlt,
  FontAwesomeIcons.bacon,
  FontAwesomeIcons.beer,
  FontAwesomeIcons.bone,
  FontAwesomeIcons.breadSlice,
  FontAwesomeIcons.carrot,
  FontAwesomeIcons.cheese,
  FontAwesomeIcons.cocktail,
  FontAwesomeIcons.cookieBite,
  FontAwesomeIcons.drumstickBite,
  FontAwesomeIcons.egg,
  FontAwesomeIcons.fish,
  FontAwesomeIcons.flask,
  FontAwesomeIcons.glassCheers,
  FontAwesomeIcons.glassMartini,
  FontAwesomeIcons.glassMartiniAlt,
  FontAwesomeIcons.glassWhiskey,
  FontAwesomeIcons.hamburger,
  FontAwesomeIcons.hotdog,
  FontAwesomeIcons.iceCream,
  FontAwesomeIcons.lemon,
  FontAwesomeIcons.mugHot,
  FontAwesomeIcons.pepperHot,
  FontAwesomeIcons.pizzaSlice,
  FontAwesomeIcons.utensilSpoon,
  FontAwesomeIcons.wineBottle,
  FontAwesomeIcons.wineGlass,
  FontAwesomeIcons.wineGlassAlt,
];

const List<IconData> objects = [
  FontAwesomeIcons.balanceScale,
  FontAwesomeIcons.balanceScaleLeft,
  FontAwesomeIcons.balanceScaleRight,
  FontAwesomeIcons.bath,
  FontAwesomeIcons.bed,
  FontAwesomeIcons.bible,
  FontAwesomeIcons.bomb,
  FontAwesomeIcons.bookReader,
  FontAwesomeIcons.broadcastTower,
  FontAwesomeIcons.bullseye,
  FontAwesomeIcons.calculator,
  FontAwesomeIcons.capsules,
  FontAwesomeIcons.chair,
  FontAwesomeIcons.clipboard,
  FontAwesomeIcons.couch,
  FontAwesomeIcons.creditCard,
  FontAwesomeIcons.cut,
  FontAwesomeIcons.dice,
  FontAwesomeIcons.diceD6,
  FontAwesomeIcons.donate,
  FontAwesomeIcons.donate,
  FontAwesomeIcons.donate,
  FontAwesomeIcons.draftingCompass,
  FontAwesomeIcons.eraser,
  FontAwesomeIcons.fax,
  FontAwesomeIcons.fireExtinguisher,
  FontAwesomeIcons.firstAid,
  FontAwesomeIcons.flagUsa,
  FontAwesomeIcons.hammer,
  FontAwesomeIcons.hanukiah,
  FontAwesomeIcons.hdd,
  FontAwesomeIcons.headphones,
  FontAwesomeIcons.highlighter,
  FontAwesomeIcons.lifeRing,
  FontAwesomeIcons.lockOpen,
  FontAwesomeIcons.magic,
  FontAwesomeIcons.magnet,
  FontAwesomeIcons.marker,
  FontAwesomeIcons.microscope,
  FontAwesomeIcons.moneyCheck,
  FontAwesomeIcons.moneyCheckAlt,
  FontAwesomeIcons.oilCan,
  FontAwesomeIcons.passport,
  FontAwesomeIcons.paste,
  FontAwesomeIcons.penFancy,
  FontAwesomeIcons.penNib,
  FontAwesomeIcons.penSquare,
  FontAwesomeIcons.pencilRuler,
  FontAwesomeIcons.photoVideo,
  FontAwesomeIcons.pills,
  FontAwesomeIcons.plug,
  FontAwesomeIcons.podcast,
  FontAwesomeIcons.quran,
  FontAwesomeIcons.ribbon,
  FontAwesomeIcons.ruler,
  FontAwesomeIcons.rulerHorizontal,
  FontAwesomeIcons.rulerVertical,
  FontAwesomeIcons.satellite,
  FontAwesomeIcons.satelliteDish,
  FontAwesomeIcons.sdCard,
  FontAwesomeIcons.shieldAlt,
  FontAwesomeIcons.shuttleVan,
  FontAwesomeIcons.simCard,
  FontAwesomeIcons.stamp,
  FontAwesomeIcons.syringe,
  FontAwesomeIcons.tablets,
  FontAwesomeIcons.thumbtack,
  FontAwesomeIcons.tint,
  FontAwesomeIcons.toiletPaper,
  FontAwesomeIcons.tv,
  FontAwesomeIcons.umbrella,
];

final List<IconData> symbols = [
  FontAwesomeIcons.ad,
  FontAwesomeIcons.angleDoubleDown,
  FontAwesomeIcons.angleDoubleLeft,
  FontAwesomeIcons.angleDoubleRight,
  FontAwesomeIcons.angleDoubleUp,
  FontAwesomeIcons.angleDown,
  FontAwesomeIcons.angleUp,
  FontAwesomeIcons.arrowAltCircleDown,
  FontAwesomeIcons.arrowAltCircleLeft,
  FontAwesomeIcons.arrowAltCircleRight,
  FontAwesomeIcons.arrowAltCircleUp,
  FontAwesomeIcons.arrowCircleDown,
  FontAwesomeIcons.arrowCircleLeft,
  FontAwesomeIcons.arrowCircleRight,
  FontAwesomeIcons.arrowCircleUp,
  FontAwesomeIcons.arrowDown,
  FontAwesomeIcons.arrowUp,
  FontAwesomeIcons.barcode,
  FontAwesomeIcons.blind,
  FontAwesomeIcons.caretDown,
  FontAwesomeIcons.caretLeft,
  FontAwesomeIcons.caretRight,
  FontAwesomeIcons.caretSquareDown,
  FontAwesomeIcons.caretSquareLeft,
  FontAwesomeIcons.caretSquareRight,
  FontAwesomeIcons.caretSquareUp,
  FontAwesomeIcons.caretUp,
  FontAwesomeIcons.chevronCircleDown,
  FontAwesomeIcons.chevronCircleLeft,
  FontAwesomeIcons.chevronCircleRight,
  FontAwesomeIcons.chevronCircleUp,
  FontAwesomeIcons.chevronDown,
  FontAwesomeIcons.chevronLeft,
  FontAwesomeIcons.chevronRight,
  FontAwesomeIcons.chevronUp,
  FontAwesomeIcons.circle,
  FontAwesomeIcons.cloudDownloadAlt,
  FontAwesomeIcons.cloudUploadAlt,
  FontAwesomeIcons.code,
  FontAwesomeIcons.copyright,
  FontAwesomeIcons.cross,
  FontAwesomeIcons.download,
  FontAwesomeIcons.exchangeAlt,
  FontAwesomeIcons.genderless,
  FontAwesomeIcons.heartBroken,
  FontAwesomeIcons.history,
  FontAwesomeIcons.inbox,
  FontAwesomeIcons.infinity,
  FontAwesomeIcons.longArrowAltDown,
  FontAwesomeIcons.longArrowAltLeft,
  FontAwesomeIcons.longArrowAltRight,
  FontAwesomeIcons.longArrowAltUp,
  FontAwesomeIcons.marsDouble,
  FontAwesomeIcons.marsStroke,
  FontAwesomeIcons.marsStrokeH,
  FontAwesomeIcons.marsStrokeV,
  FontAwesomeIcons.mercury,
  FontAwesomeIcons.neuter,
  FontAwesomeIcons.parking,
  FontAwesomeIcons.peace,
  FontAwesomeIcons.percent,
  FontAwesomeIcons.percentage,
  FontAwesomeIcons.qrcode,
  FontAwesomeIcons.reply,
  FontAwesomeIcons.retweet,
  FontAwesomeIcons.share,
  FontAwesomeIcons.shareAlt,
  FontAwesomeIcons.shareSquare,
  FontAwesomeIcons.signInAlt,
  FontAwesomeIcons.signOutAlt,
  FontAwesomeIcons.smokingBan,
  FontAwesomeIcons.starAndCrescent,
  FontAwesomeIcons.starOfDavid,
  FontAwesomeIcons.sync,
  FontAwesomeIcons.syncAlt,
  FontAwesomeIcons.trademark,
  FontAwesomeIcons.transgender,
  FontAwesomeIcons.transgenderAlt,
  FontAwesomeIcons.undo,
  FontAwesomeIcons.undoAlt,
  FontAwesomeIcons.upload,
  FontAwesomeIcons.venusDouble,
  FontAwesomeIcons.venusMars,
  FontAwesomeIcons.volumeDown,
  FontAwesomeIcons.volumeMute,
  FontAwesomeIcons.volumeOff,
  FontAwesomeIcons.volumeUp,
  FontAwesomeIcons.wheelchair,
  FontAwesomeIcons.yinYang,
];

final List<IconData> travelAndPlaces = [
  FontAwesomeIcons.ambulance,
  FontAwesomeIcons.anchor,
  FontAwesomeIcons.archway,
  FontAwesomeIcons.building,
  FontAwesomeIcons.bus,
  FontAwesomeIcons.busAlt,
  FontAwesomeIcons.campground,
  FontAwesomeIcons.carCrash,
  FontAwesomeIcons.carSide,
  FontAwesomeIcons.chargingStation,
  FontAwesomeIcons.church,
  FontAwesomeIcons.city,
  FontAwesomeIcons.clinicMedical,
  FontAwesomeIcons.directions,
  FontAwesomeIcons.gasPump,
  FontAwesomeIcons.hospital,
  FontAwesomeIcons.hospitalAlt,
  FontAwesomeIcons.hotel,
  FontAwesomeIcons.houseDamage,
  FontAwesomeIcons.industry,
  FontAwesomeIcons.kaaba,
  FontAwesomeIcons.mapPin,
  FontAwesomeIcons.monument,
  FontAwesomeIcons.mosque,
  FontAwesomeIcons.motorcycle,
  FontAwesomeIcons.parachuteBox,
  FontAwesomeIcons.placeOfWorship,
  FontAwesomeIcons.planeArrival,
  FontAwesomeIcons.planeDeparture,
  FontAwesomeIcons.restroom,
  FontAwesomeIcons.road,
  FontAwesomeIcons.route,
  FontAwesomeIcons.school,
  FontAwesomeIcons.ship,
  FontAwesomeIcons.subway,
  FontAwesomeIcons.synagogue,
  FontAwesomeIcons.taxi,
  FontAwesomeIcons.toriiGate,
  FontAwesomeIcons.tractor,
  FontAwesomeIcons.trafficLight,
  FontAwesomeIcons.train,
  FontAwesomeIcons.tram,
  FontAwesomeIcons.truck,
  FontAwesomeIcons.truckMonster,
  FontAwesomeIcons.truckPickup,
  FontAwesomeIcons.umbrellaBeach,
  FontAwesomeIcons.vihara,
  FontAwesomeIcons.warehouse,
];

List<List<dynamic>> convertCategoryToItems(
    List<IconData> category, String title) {
  List<List<dynamic>> sumList = [
    [title]
  ];

  for (var i = 0; i <= category.length - 1; i = i + 5) {
    sumList.add([
      category[i],
      i + 1 > category.length - 1 ? null : category[i + 1],
      i + 2 > category.length - 1 ? null : category[i + 2],
      i + 3 > category.length - 1 ? null : category[i + 3],
      i + 4 > category.length - 1 ? null : category[i + 4],
    ]);
  }

  return sumList;
}

final List<List<dynamic>> allIconsList = [
  ...convertCategoryToItems(interfaceEssentials, 'Interface Essentials'),
  ...convertCategoryToItems(animalsAndNature, 'Animals & Nature'),
  ...convertCategoryToItems(facesAndClothing, 'Smileys & People'),
  ...convertCategoryToItems(foodAndDrinks, 'Food & Drink'),
  ...convertCategoryToItems(objects, 'Objects'),
  ...convertCategoryToItems(symbols, 'Symbols'),
  ...convertCategoryToItems(travelAndPlaces, 'Travel & Places'),
];
